---
title: "TDM"
author: "Reid Haefer"
date: "November 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, osmdata, sf, leaflet, tmap, spDataLarge, stplanr, geojsonio, mapview)
```

## lime analysis

```{r, message=F, warning=F, echo=F}
lime <- read_csv("H:/model/network_analyst/Lime Network Analyst/TRIPS_2018_september.csv")

taz<- geojson_read("https://opendata.arcgis.com/datasets/8753e4259d7b464ead6a4b5be99f2346_6.geojson", what="sp") %>% st_as_sf() %>% select(TAZ)

o <- lime %>% select(trip_id, start_latitude, start_longitude) %>%
  st_as_sf(coords= c("start_longitude","start_latitude"), crs=4326) %>%
  st_join(taz)

d <- lime %>% select(trip_id, end_latitude, end_longitude) %>%
  st_as_sf(coords= c("end_longitude","end_latitude"), crs=4326) %>%
  st_join(taz)

od <- data.frame(o) %>% left_join(data.frame(d), by="trip_id") %>%
  count(TAZ.x, TAZ.y)

d_line<- od2line(od, taz) %>% filter(!is.na(TAZ.x)) %>% filter(!is.na(TAZ.y))

d_line$distance <- as.numeric(st_length(d_line))

route <- line2route(d_line, route_fun = route_osrm)

d_line$geom_car <- st_geometry(route)

final <- d_line %>% select(-geometry) %>%
  rename(start_taz=TAZ.x, end_taz=TAZ.y, trips=n) %>%
  mutate(id=paste0(start_taz, end_taz))

end <- final %>%

sub('.*\\.', '', x)

test <- final %>% data.frame() %>% select(start_taz, end_taz) 

test1<-unique(t(apply(test, 1, sort))) %>% data.frame() %>% mutate(route_id = paste(X1, X2, sep="-"))

test1<-unique(t(apply(test, 1, sort))) %>% data.frame() %>% mutate(route_id = paste(X2, X1, sep="-"))

duplicated(t(apply(test, 1, sort)))

popup <- paste0("<br><strong>Origin TAZ </strong>", 
                final$TAZ.x,
                "<br><strong>Destination TAZ: </strong>", 
               final$TAZ.y,
                "<br><strong>Number of Trips: </strong>", 
                final$n)

pal <- colorNumeric(
  palette = "Blues",
  domain = final$n)

leaflet(final) %>% addPolylines(popup=popup, color = ~pal(n)) %>% addTiles()

st_write(final, "H:/model/network_analyst", "lime", driver= "ESRI Shapefile", delete_layer = T)

```


```{r}
taz<- geojson_read("https://opendata.arcgis.com/datasets/8753e4259d7b464ead6a4b5be99f2346_6.geojson", what="sp") %>% st_as_sf() %>% select(TAZ)
  
taz_zone<- taz %>% filter(TAZ %in% c(9,39,111,200))

taz_od <- data.frame(o=c(9,9,9,39,39,39,111,111,111,200,200,200),
             d=c(39,111,200,9,111,200, 9,39,200,9,39,111),
             flow=c(12,100, 44,9, 78,66,19,50,88,44,2,40))

desire_lines <- od2line(taz_od,taz_zone)

qtm(desire_lines, lines.lwd = "flow")

desire_lines$distance <- as.numeric(st_length(desire_lines))

route <- line2route(desire_lines, route_fun = route_osrm)

desire_lines$geom_car = st_geometry(route)

mapview::mapview(desire_lines$geom_car)

leaflet(desire_lines$geom_car) %>% addPolylines() %>% addTiles()

tmap_mode("view")
tm_shape(desire_lines$geom_car) + tm_lines()
```

```{r}

### bristol example
bristol_region <-  osmdata::getbb("Bristol", format_out = "sf_polygon")
zones_attr <- bristol_od %>% 
  group_by(o) %>% 
  summarize_if(is.numeric, sum) %>% 
  dplyr::rename(geo_code = o)
zones_joined <- left_join(bristol_zones, zones_attr, by = "geo_code")

zones_od <- bristol_od %>% 
  group_by(d) %>% 
  summarize_if(is.numeric, sum) %>% 
  dplyr::select(geo_code = d, all_dest = all) %>% 
  inner_join(zones_joined, ., by = "geo_code")

qtm(zones_od, c("all", "all_dest")) +
  tm_layout(panel.labels = c("Origin", "Destination"))

bristol_od$Active <- (bristol_od$bicycle + bristol_od$foot) /
  bristol_od$all * 100

od_intra <- filter(bristol_od, o == d)
od_inter <- filter(bristol_od, o != d)

desire_lines <- od2line(od_inter, zones_od)

qtm(desire_lines, lines.lwd = "all")

desire_lines$distance <- as.numeric(st_length(desire_lines))
desire_carshort <- dplyr::filter(desire_lines, car_driver > 300 & distance < 5000)

route_carshort <- line2route(desire_carshort, route_fun = route_osrm)

desire_carshort$geom_car <- st_geometry(route_carshort)

mapview::mapview(desire_carshort$geom_car)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
